WIP: Anomaly detection module
astrolabsoftware/fink-science pull request #265
Opened 2022-12-09 19:16 UTC by VoidDruid

_work in progress, right now this PR only for review and CI pipeline cheks_

Linked to issue(s): first step to closing[ anomaly detection issue](https://github.com/astrolabsoftware/fink-science/issues/264)

## If this is a new release, did you issue the corresponding schema in fink-client?

PR in broker - _TODO_

## What changes were proposed in this pull request?

Add `anomaly_score` column for anomaly detection pipeline.

## How was this patch tested?

Doctests, in jupyter with fink test data, and manual testing.

2023-01-10 18:47 UTC, JulienPeloton requested changes
Thanks @VoidDruid for the new module! Some comments on the models:
- models should be put in the folder `fink_science/data/models` with all the others (and the path should be updated accordingly)
- the two models together are about 40MB. This repository, with models, is packaged and distributed on pypi which has a hard limit of 100MB for each repository. Is there any chance you can make your models slimmer?

2023-01-10 18:51 UTC, JulienPeloton commented on fink_science/anomaly_detection/processor.py
> +with open(f"{path}/anomaly_detection/forest_r.pickle", 'rb') as forest_file:
Change the path to `data/models` using:

```python
from fink_science import __file__

...
path = os.path.dirname(os.path.abspath(__file__))
model_path = curdir + '/data/models/forest_r.pickle'
with open(model_path, 'rb') as forest_file:
  ...
...
```

2023-01-10 18:52 UTC, JulienPeloton commented on fink_science/anomaly_detection/processor.py
> +with open(f"{path}/anomaly_detection/forest_g.pickle", 'rb') as forest_file:
Change the path to data/models using:

```python
from fink_science import __file__

...
path = os.path.dirname(os.path.abspath(__file__))
model_path = curdir + '/data/models/forest_r.pickle'
with open(model_path, 'rb') as forest_file:
  ...
```

2023-01-17 12:18 UTC, VoidDruid commented on fink_science/anomaly_detection/processor.py
> +with open(f"{path}/anomaly_detection/forest_r.pickle", 'rb') as forest_file:
Done

2023-01-17 12:18 UTC, VoidDruid commented on fink_science/anomaly_detection/processor.py
> +with open(f"{path}/anomaly_detection/forest_g.pickle", 'rb') as forest_file:
Done

2023-01-17 12:24 UTC, VoidDruid commented
>      models should be put in the folder `fink_science/data/models` with all the others (and the path should be updated accordingly)

Done

>      the two models together are about 40MB. This repository, with models, is packaged and distributed on pypi which has a hard limit of 100MB for each repository. Is there any chance you can make your models slimmer?

Put pickle files into a zip archive, which will unzip on first module import, zip archive is ~13mb.

2023-01-17 14:51 UTC, JulienPeloton approved these changes
Thanks @VoidDruid ! All good to me, I will merge this PR, and move to the PR in fink-broker to add the module.

2023-01-17 14:51 UTC, merged