New filter for orphan afterglows
astrolabsoftware/fink-science pull request #403
Opened 2024-07-24 13:02 UTC by marinamasson

Linked to issue(s): Closes #402 

## If this is a new release, did you issue the corresponding schema in fink-client?

This is a new module, not a new release.

## What changes were proposed in this pull request?

A new science module.

How is the issue this PR is referenced against solved with this PR?

The PR solves the issue.

## How was this patch tested?

Not tested within Fink.

2024-10-07 07:35 UTC, JulienPeloton requested changes
Thanks @marinamasson ! I have done a first pass on the code, and left some comments. I will perform a profiling of the code, and paste the results here later this week.

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter.py
> +from filter_utils import compute_duration_between_first_and_peak, compute_rate, compute_color, fit_light_curve
To avoid name conflicts, the import should always be absolute:

```python
from fink_science.orphans.filter_utils import ...
```

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter.py
> +from pyspark.sql.functions import pandas_udf, PandasUDFType
All files should start with the header containing the license statement & authorship (see other modules for example)

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter.py
> +    # `True` for the objects that have a probability > 0.999999 to be an orphan, else `False`
For more flexibility, we usually decouple the computation of a quantity (fink science module), and the relevant threshold(s) to be applied on this quantity (fink filter). Hence I would suggest to return the probability values here, and then design a filter in [fink-filters](https://github.com/astrolabsoftware/fink-filters).

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +import numpy as np
All files should start with the header containing the license statement & authorship (see other modules for example)

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +# =======================================================================================================================
These two commented lines are unnecessary here.

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +# =======================================================================================================================
These two commented lines are unnecessary here.

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +    Save the number of days between the first detection and the peak, and the date of the first detection
This description is not clear to me :-)

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +    Save the number of days between the first detection and the peak, and the date of the first detection
The description is not correct?

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +# =======================================================================================================================
These two commented lines are unnecessary here.

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +    all_mean_nu = [840336134453781.4, 629326620516047.8, 482703137570394.2, 397614314115308.1, 344530577088716.56,
Where this `all_mean_nu` comes from? Is it specific to a dataset? Does it need to be updated if the input dataset change (elasticc --> lsst)?

2024-10-07 07:35 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +        # choose values of -beta between -(p-1)/2 and -p/2
What is `p`?

2025-04-09 07:42 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +    all_mean_nu = [840336134453781.4, 629326620516047.8, 482703137570394.2, 397614314115308.1, 344530577088716.56,
ping :-)

2025-04-09 07:51 UTC, JulienPeloton reviewed
Thanks @marinamasson -- sorry for the delay in getting back to you. There are still inconsistencies to use this properly with Apache Spark (I can see that your code for Elasticc was using purely pandas). I will let you handle my last comment (see below), and if you are ok, I will make the modifications myself to integrate it with Spark.

2025-04-09 07:51 UTC, JulienPeloton commented on fink_science/orphans/processor.py
> +def orphan_grb(ctimemjd, cabmags, cabmagserr, cfilts):
This should have a decorator for Spark, namely:

```python
from pyspark.sql.functions import pandas_udf
from pyspark.sql.types import FloatType

@pandas_udf(FloatType())
def orphan_grb(ctimemjd, cabmags, cabmagserr, cfilts):
...
```

2025-04-14 11:47 UTC, marinamasson commented on fink_science/orphans/filter_utils.py
> +    all_mean_nu = [840336134453781.4, 629326620516047.8, 482703137570394.2, 397614314115308.1, 344530577088716.56,
This `all_mean_nu` are the mean frequencies for LSST photometric filters, that I computed. There should be no need to update it.

2025-04-14 12:10 UTC, marinamasson commented on fink_science/orphans/processor.py
> +def orphan_grb(ctimemjd, cabmags, cabmagserr, cfilts):
Thanks @JulienPeloton for your review! I'm completely ok if you can make the modifications to integrate it with Spark. Don't hesitate if more things need to be modified from my side.

2025-04-16 05:31 UTC, JulienPeloton commented on fink_science/orphans/filter_utils.py
> +    all_mean_nu = [840336134453781.4, 629326620516047.8, 482703137570394.2, 397614314115308.1, 344530577088716.56,
Thanks!

2025-04-16 05:33 UTC, merged